using System.Collections.Concurrent;
using System.Runtime.CompilerServices;
using System.Threading.Channels;

namespace RazorX.Framework;

/// <summary>
/// Provides a thread-safe broadcast service for distributing SSE updates to multiple connected clients.
/// </summary>
/// <typeparam name="T">The model type to broadcast to subscribers.</typeparam>
/// <remarks>
/// <para>
/// This is an optional utility for scenarios where multiple clients should receive the same real-time updates,
/// such as live dashboards, notifications, collaborative editing, or activity feeds.
/// </para>
/// <para>
/// <strong>Registration:</strong> Register as singleton in dependency injection:
/// <code>builder.Services.AddSingleton&lt;RxSseBroadcastService&lt;MyModel&gt;&gt;();</code>
/// </para>
/// <para>
/// <strong>Architecture:</strong> Each subscriber receives an isolated Channel for thread-safe message delivery.
/// When BroadcastUpdate() is called, the update is written to ALL subscriber channels in parallel.
/// </para>
/// <para>
/// <strong>Limitations:</strong> This is a simple in-memory broadcast utility with no authorization,
/// user-scoping, or filtering. For advanced scenarios (user-specific channels, role-based access,
/// topic routing), wrap this service or implement a custom broadcast service.
/// </para>
/// <para>
/// <strong>Memory Management:</strong> Always call Unsubscribe() when done, or use CancellationToken.Register()
/// for automatic cleanup when clients disconnect.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Initialize subscriber ID in initial page load (session auto-commits at request end)
/// public static async Task&lt;IResult&gt; GetPage(HttpContext context, IRxDriver rxDriver) {
///     var subscriberId = context.Session.GetString("SubscriberId");
///     if (string.IsNullOrWhiteSpace(subscriberId)) {
///         subscriberId = Guid.NewGuid().ToString();
///         context.Session.SetString("SubscriberId", subscriberId);
///     }
///     return await rxDriver.RenderPage&lt;Layout, Page&gt;(context);
/// }
///
/// // In SSE handler - Subscribe using session-based ID
/// public static IResult StreamUpdates(
///     HttpContext context,
///     IRxDriver rxDriver,
///     RxSseBroadcastService&lt;TodoModel&gt; broadcast,
///     CancellationToken ct)
/// {
///     var subscriberId = context.Session.GetString("SubscriberId")!;
///
///     if (!broadcast.HasSubscriber(subscriberId)) {
///         broadcast.Subscribe(subscriberId);
///         ct.Register(() => broadcast.Unsubscribe(subscriberId));
///     }
///
///     return rxDriver
///         .With(context)
///         .RenderSse(
///             broadcast.GetUpdates(subscriberId, ct),
///             async (todo, builder) => builder.AddFragment&lt;TodoCard&gt;(todo, "todo-list", Beforeend),
///             ct
///         );
/// }
///
/// // In regular handler - Broadcast with echo suppression
/// public static async Task&lt;IResult&gt; UpdateTodo(
///     HttpContext context,
///     IRxDriver rxDriver,
///     RxSseBroadcastService&lt;TodoModel&gt; broadcast,
///     TodoModel todo)
/// {
///     await repository.SaveAsync(todo);
///
///     // Exclude triggering client to prevent echo
///     var excludeId = context.Session.GetString("SubscriberId");
///     await broadcast.BroadcastUpdate(todo, excludeId);
///
///     return await rxDriver
///         .With(context)
///         .AddFragment&lt;TodoCard&gt;(todo, $"todo-{todo.Id}", Swap)
///         .Render();
/// }
/// </code>
/// </example>
public sealed class RxSseBroadcastService<T> : IDisposable {
    private readonly ConcurrentDictionary<string, Channel<T>> _subscribers = new();
    private bool _disposed = false;

    /// <summary>
    /// Subscribes a client with the specified subscriber ID.
    /// </summary>
    /// <param name="subscriberId">The subscriber ID to register (typically from session, user ID, or application-generated identifier).</param>
    /// <returns>True if the subscriber was added; false if a subscriber with this ID already exists.</returns>
    /// <remarks>
    /// <para>
    /// Each subscriber receives an isolated unbounded channel for message delivery.
    /// The subscriber ID is application-provided (not generated by this service).
    /// </para>
    /// <para>
    /// <strong>Recommended pattern:</strong> Use session-based IDs initialized in RenderPage:
    /// <code>
    /// // In RenderPage (session auto-commits at request end)
    /// var id = context.Session.GetString("SubscriberId");
    /// if (string.IsNullOrWhiteSpace(id)) {
    ///     id = Guid.NewGuid().ToString();
    ///     context.Session.SetString("SubscriberId", id);
    /// }
    /// </code>
    /// </para>
    /// <para>
    /// Always call Unsubscribe() when done, or use CancellationToken.Register() for automatic cleanup.
    /// </para>
    /// </remarks>
    public bool Subscribe(string subscriberId) {
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        var channel = Channel.CreateUnbounded<T>(new UnboundedChannelOptions {
            SingleReader = true,   // Each channel has one reader (the SSE stream)
            SingleWriter = false   // Multiple writers (broadcast can write to all channels)
        });
        return _subscribers.TryAdd(subscriberId, channel);
    }

    /// <summary>
    /// Unsubscribes a client and completes their channel.
    /// </summary>
    /// <param name="subscriberId">The subscriber ID to unsubscribe.</param>
    /// <remarks>
    /// This method is idempotent - calling it multiple times with the same ID is safe.
    /// The channel is completed gracefully, allowing any pending reads to finish.
    /// </remarks>
    public void Unsubscribe(string subscriberId) {
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        if (_subscribers.TryRemove(subscriberId, out var channel)) {
            try {
                channel.Writer.Complete();
            } catch {
                // Channel may already be completed - ignore
            }
        }
    }

    /// <summary>
    /// Broadcasts an update to ALL connected subscribers in parallel.
    /// </summary>
    /// <param name="model">The model to broadcast to all subscribers.</param>
    /// <param name="excludeSubscriberId">Optional subscriber ID to exclude from the broadcast (typically the client that triggered the update).</param>
    /// <remarks>
    /// <para>
    /// Writes to all subscriber channels in parallel using Task.WhenAll.
    /// If a channel fails (subscriber disconnected), the error is caught and doesn't affect other subscribers.
    /// </para>
    /// <para>
    /// <strong>Echo Suppression:</strong> Use excludeSubscriberId to prevent the triggering client from receiving
    /// their own update via SSE (they already received it via the AJAX response). This is the recommended pattern
    /// for avoiding duplicate updates.
    /// </para>
    /// <para>
    /// <strong>Thread Safety:</strong> Safe to call from multiple threads simultaneously.
    /// </para>
    /// <para>
    /// <strong>Performance:</strong> Completes when ALL channels have received the message (parallel write).
    /// </para>
    /// </remarks>
    public async Task BroadcastUpdate(T model, string? excludeSubscriberId = null) {
        ArgumentNullException.ThrowIfNull(model);
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        if (_subscribers.IsEmpty) {
            return;  // No subscribers, nothing to do
        }
        var tasks = _subscribers
            .Where(kvp => excludeSubscriberId == null || kvp.Key != excludeSubscriberId)  // Filter out excluded subscriber
            .Select(async kvp => {
                try {
                    await kvp.Value.Writer.WriteAsync(model);
                } catch (ChannelClosedException) {
                    // Channel was completed/closed - subscriber disconnected
                    // This is expected and normal, don't propagate exception
                } catch {
                    // Unexpected error - don't fail entire broadcast
                    // Individual channel errors don't affect other subscribers
                }
            });
        await Task.WhenAll(tasks);
    }

    /// <summary>
    /// Gets an async stream of updates for a specific subscriber.
    /// </summary>
    /// <param name="subscriberId">The subscriber ID that was registered with Subscribe().</param>
    /// <param name="cancellationToken">Cancellation token to stop the stream (typically HttpContext.RequestAborted).</param>
    /// <returns>An async enumerable of updates for this subscriber.</returns>
    /// <remarks>
    /// <para>
    /// This method is typically called within RenderSse() to provide the model stream.
    /// The stream continues until the channel is completed or the cancellation token is triggered.
    /// </para>
    /// <para>
    /// If the subscriber ID is not found (invalid or not yet subscribed), the stream ends immediately (yield break).
    /// </para>
    /// </remarks>
    public async IAsyncEnumerable<T> GetUpdates(
        string subscriberId,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        if (!_subscribers.TryGetValue(subscriberId, out var channel)) {
            yield break;  // Subscriber not found
        }
        await foreach (var update in channel.Reader.ReadAllAsync(cancellationToken)) {
            yield return update;
        }
    }

    /// <summary>
    /// Gets the count of currently active SSE connections.
    /// </summary>
    /// <returns>The number of active subscribers.</returns>
    /// <remarks>
    /// Useful for monitoring and diagnostics. The count includes only active subscribers
    /// that have called Subscribe() but not yet Unsubscribe().
    /// </remarks>
    public int GetActiveConnectionCount() {
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        return _subscribers.Count;
    }

    /// <summary>
    /// Gets a list of all active subscriber IDs.
    /// </summary>
    /// <returns>Read-only list of subscriber IDs.</returns>
    /// <remarks>
    /// Useful for diagnostics and debugging. The list is a snapshot at the time of the call.
    /// </remarks>
    public IReadOnlyList<string> GetActiveSubscribers() {
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        return [.. _subscribers.Keys];
    }

    /// <summary>
    /// Checks if a subscriber with the specified ID is currently subscribed.
    /// </summary>
    /// <param name="subscriberId">The subscriber ID to check.</param>
    /// <returns>True if a subscriber with this ID exists; otherwise false.</returns>
    /// <remarks>
    /// Useful for checking if a subscriber already exists before calling Subscribe() to avoid duplicate subscriptions.
    /// </remarks>
    public bool HasSubscriber(string subscriberId) {
        ObjectDisposedException.ThrowIf(_disposed, nameof(RxSseBroadcastService<>));
        return _subscribers.ContainsKey(subscriberId);
    }

    /// <summary>
    /// Disposes the broadcast service and completes all subscriber channels.
    /// </summary>
    /// <remarks>
    /// Called automatically when the application shuts down (registered as singleton).
    /// Completes all channels gracefully, allowing pending reads to finish.
    /// </remarks>
    public void Dispose() {
        if (_disposed) {
            return;
        }
        // Complete all channels
        foreach (var channel in _subscribers.Values) {
            try {
                channel.Writer.Complete();
            } catch {
                // Ignore errors during disposal
            }
        }
        _subscribers.Clear();
        _disposed = true;
    }
}
