<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RazorX.Framework\RazorX.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest" Version="3.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <Target Name="NodeInstall" BeforeTargets="Compile" Condition="!Exists('Node/node_modules')">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <!-- Install npm packages -->
    <Message Importance="High" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="Node" Command="npm install" />
  </Target>

  <Target Name="CopyTsFiles" AfterTargets="Compile">
    <ItemGroup>
      <TsFiles Include="../RazorX.Framework/Node/src/*.*"/>
    </ItemGroup>
    <Copy SourceFiles="@(TsFiles)" DestinationFolder="Node/src" />
  </Target>

</Project>
